version: '3'

services:

  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ['CMD_SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  educational_module:
    build: .
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/educational_modules
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

volumes:
  postgres_data:
